export const mockProblems = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    acceptanceRate: 49.2,
    tags: ["Array", "Hash Table"],
    status: "solved",
  },
  {
    id: 2,
    title: "Add Two Numbers",
    difficulty: "Medium",
    acceptanceRate: 38.1,
    tags: ["Linked List", "Math"],
    status: "attempted",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    acceptanceRate: 33.8,
    tags: ["Hash Table", "String", "Sliding Window"],
    status: "unsolved",
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    acceptanceRate: 35.2,
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    status: "unsolved",
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    acceptanceRate: 32.4,
    tags: ["String", "Dynamic Programming"],
    status: "solved",
  },
  {
    id: 6,
    title: "ZigZag Conversion",
    difficulty: "Medium",
    acceptanceRate: 42.1,
    tags: ["String"],
    status: "unsolved",
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Medium",
    acceptanceRate: 27.3,
    tags: ["Math"],
    status: "attempted",
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    acceptanceRate: 16.4,
    tags: ["String"],
    status: "unsolved",
  },
];

export const allTags = [
  "Array",
  "Hash Table",
  "Linked List",
  "Math",
  "String",
  "Dynamic Programming",
  "Binary Search",
  "Divide and Conquer",
  "Sliding Window",
];
